# CSE 5000 – Information to Information Technology  
## Lecture 1: From Data to Information Systems  
**Module:** Digital Infrastructure & Computing Foundations  
**Duration:** 1 hour 20 minutes  

---

## 1. Introduction: Why Managers Must Understand Information Systems  

Modern organizations do not merely use information systems; they operate through them. Every managerial decision—pricing, hiring, logistics, marketing, or risk management—is increasingly mediated by information systems that collect, process, and distribute data in real time.

Laudon and Laudon define an information system as *“a set of interrelated components that collect (or retrieve), process, store, and distribute information to support decision making, coordination, and control in an organization.”*  
(Laudon & Laudon, *Management Information Systems*, 16th ed., Chapter 1, Section 1.1, pp. 4–6)

This definition highlights that information systems are not purely technical artefacts. They are socio-technical systems embedded in organizational structures, human behavior, and institutional rules.

**Managerial relevance:**  
When a manager reviews a sales dashboard, approves a loan, or authorizes a procurement order, they are relying on outputs generated by an information system. Understanding how those outputs are produced is essential for judging their accuracy, limitations, and strategic implications.

---

## 2. Data, Information, and Knowledge  

A foundational distinction in information systems literature is between data, information, and knowledge.

According to Laudon and Laudon (Chapter 1, Section 1.1, pp. 6–8):

- **Data** are raw facts representing events before they have been organized or processed.
- **Information** is data that have been organized into a meaningful and useful form.
- **Knowledge** consists of insights, patterns, and rules derived from information and experience.

### Practical illustration  
A retail system records the following:
- Transaction time  
- Product ID  
- Quantity sold  
- Sale price  

These are data.  
When aggregated into a daily sales report, they become information.  
When managers analyze repeated patterns to decide which products to promote or discontinue, this becomes knowledge.

### Link to current trends  
In the era of big data and artificial intelligence, organizations often collect vast volumes of data but fail to convert them into actionable knowledge. Research consistently shows that the main challenge lies not in data availability but in managerial interpretation and decision-making capability.

Further reading:  
https://www.mckinsey.com/capabilities/quantumblack/our-insights

---

## 3. The Five-Component Model of an Information System  

Laudon and Laudon identify five core components common to all information systems (Chapter 1, Section 1.2, pp. 9–14):

1. **Hardware** – physical devices such as servers, computers, mobile devices, and sensors  
2. **Software** – operating systems and application programs  
3. **Data** – stored facts and figures relevant to organizational operations  
4. **Procedures** – rules and instructions governing system use  
5. **People** – end users, managers, and IT professionals  

This model emphasizes that failures in information systems often occur not because of hardware or software problems, but due to poorly designed procedures or insufficient user understanding.

### In-class demonstration  
Trace a single online food delivery order:
- Hardware: smartphone, cloud server, GPS device  
- Software: mobile app, backend services  
- Data: order details, customer location, payment confirmation  
- Procedures: order validation, dispatch rules  
- People: customer, restaurant staff, delivery rider  

---

## 4. Information Systems and Organizational Levels  

Information systems support different levels of organizational activity (Laudon & Laudon, Chapter 1, Section 1.3, pp. 14–18):

- **Operational-level systems** support routine daily transactions (e.g., transaction processing systems).
- **Management-level systems** support monitoring, control, and short-term decision-making.
- **Strategic-level systems** support long-term planning and competitive advantage.

### Example  
In a ride-sharing platform:
- Operational systems match drivers with riders in real time.
- Management systems generate weekly performance reports.
- Strategic systems analyze long-term demand patterns for market expansion.

This layered structure explains why disruptions at the operational level can escalate into strategic risks.

---

## 5. Information Systems as Socio-Technical Systems  

Information systems are socio-technical systems, meaning their effectiveness depends on the interaction between technology and social factors such as organizational culture, incentives, skills, and power relations (Laudon & Laudon, Chapter 1, Section 1.2).

### Empirical case: ERP implementation failures  
Many ERP projects fail not because the software is defective, but because employees resist new processes or lack adequate training.

Reference case overview:  
https://sloanreview.mit.edu/article/why-erp-projects-fail/

This perspective prepares managers to diagnose IT problems beyond purely technical explanations.

---

## 6. Live Demonstration: Transaction Flow  

**Suggested in-class activity:**  
Demonstrate how a simple sales transaction flows through:
1. User interface  
2. Application logic  
3. Database  
4. Management report or dashboard  

This reinforces how abstract concepts discussed earlier operate within real systems.

Supplementary video:  
https://www.youtube.com/watch?v=0iZzYpZx1Jk

---

## 7. Student Engagement Tasks  

**Task 1:**  
Identify one information system you use daily and describe it using the five-component model.

**Task 2:**  
Find a recent news article describing a digital system failure (e.g., bank outage, airline disruption). Identify whether the failure was primarily technical, procedural, or human.

Suggested source:  
https://www.bbc.com/news/technology

---

## 8. Key Takeaways  

This lecture establishes the conceptual foundation for the course. Students should understand that:
- Information systems are more than just technology.
- Data only becomes valuable through processing and interpretation.
- Effective management requires systems literacy rather than programming expertise.

---

## Required Reading (Before Lecture 2)
- Laudon, K. C., & Laudon, J. P. *Management Information Systems*, 16th ed.  
  - Chapter 1, Sections 1.1–1.3
